name: Build and Release Python App

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag Name (e.g., v1.0.0)'
        required: true
      release_name:
        description: 'Release Name (e.g., First Release)'
        required: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools wheel pyinstaller
          pip install -r requirements.txt

      - name: Build Windows App
        run: pyinstaller --onefile --noconsole --add-data "il_plaka.json;." main.py

      - name: List Windows Build Directory
        run: dir dist\

      - name: Zip Windows Build
        run: |
          cd dist
          powershell Compress-Archive -Path *.exe -DestinationPath NamazZamani_windows.zip

      - name: Upload Windows Build as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: dist\NamazZamani_windows.zip

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install py2app --use-pep517

      - name: Build Mac App
        run: python setup.py py2app

      - name: List Mac Build Directory
        run: ls -R dist/

      - name: Zip Mac Build
        run: |
          cd dist
          zip NamazZamani_mac.zip main

      - name: Upload Mac Build as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-app
          path: dist/NamazZamani_mac.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools wheel pyinstaller
          pip install -r requirements.txt

      - name: Build Linux App
        run: pyinstaller --onefile --noconsole --add-data "il_plaka.json:." main.py

      - name: List Linux Build Directory
        run: ls -R dist/

      - name: Zip Linux Build
        run: |
          cd dist
          zip NamazZamani_linux.zip main

      - name: Upload Linux Build as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-app
          path: dist/NamazZamani_linux.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-mac, build-linux]
    steps:
      - uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-app
          path: ./windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-app
          path: ./linux

      - name: Download Mac Artifact
        uses: actions/download-artifact@v3
        with:
          name: mac-app
          path: ./mac

      - name: List Directories After Download
        run: |
          echo "Windows Build:"
          ls -R ./windows
          echo "Mac Build:"
          ls -R ./mac
          echo "Linux Build:"
          ls -R ./linux

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body: "Automatically generated release."
          draft: false
          prerelease: false

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows/dist/NamazZamani_windows.zip
          asset_name: NamazZamani_${{ github.event.inputs.tag_name }}_windows.zip
          asset_content_type: application/zip

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux/dist/NamazZamani_linux.zip
          asset_name: NamazZamani_${{ github.event.inputs.tag_name }}_linux.zip
          asset_content_type: application/zip

      - name: Upload Mac Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mac/dist/NamazZamani_mac.zip
          asset_name: NamazZamani_${{ github.event.inputs.tag_name }}_mac.zip
          asset_content_type: application/zip
