name: Build and Release Python App

on:
  workflow_dispatch:  # Manuel tetikleme için
    inputs:
      tag_name:
        description: 'Sürüm Tag İsmi (Örneğin: v1.0.0)'
        required: true
      release_name:
        description: 'Release İsmi (Örneğin: İlk Sürüm)'
        required: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2  # Kodu indir

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools wheel pyinstaller
          pip install -r requirements.txt

      - name: Build Windows App
        run: pyinstaller --onefile --noconsole --add-data "il_plaka.json;." main.py

      - name: List Windows Build Directory
        run: ls -R dist/

      - name: Upload Windows Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: dist/*.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install py2app --use-pep517

      - name: Build Mac App
        run: python setup.py py2app

      - name: List Mac Build Directory
        run: ls -R dist/

      - name: Upload Mac Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: dist/*.app

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools wheel pyinstaller
          pip install -r requirements.txt

      - name: Build Linux App
        run: pyinstaller --onefile --noconsole --add-data "il_plaka.json:." main.py

      - name: List Linux Build Directory
        run: ls -R dist/

      - name: Upload Linux Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: dist/main  # PyInstaller'ın oluşturduğu dosya adını kesinlikle kontrol edin

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-mac, build-linux]  # Tüm build işlemleri tamamlandıktan sonra
    steps:
      - uses: actions/checkout@v2

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-app
          path: ./windows

      - name: Download Mac Artifact
        uses: actions/download-artifact@v4
        with:
          name: mac-app
          path: ./mac

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-app
          path: ./linux

      - name: List Windows Directory After Download
        run: ls -R ./windows
        
      - name: List Mac Directory After Download
        run: ls -R ./mac
        
      - name: List Linux Directory After Download
        run: ls -R ./linux

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body: "Otomatik olarak oluşturulmuş sürüm."
          draft: false
          prerelease: false

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows/dist/*.exe  # Windows için
          asset_name: windows-app.zip
          asset_content_type: application/octet-stream

      - name: Upload Mac Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mac/dist/*.app  # Mac için
          asset_name: mac-app.zip
          asset_content_type: application/octet-stream

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux/dist/main  # Linux için
          asset_name: linux-app.zip
          asset_content_type: application/octet-stream
